---
name: Build and Test fzf for Ubuntu

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  LANG: C.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.20"

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install packages
      run: sudo apt-get install --yes zsh fish tmux

    - name: Install Ruby gems
      run: sudo gem install --no-document minitest:5.17.0 rubocop:1.43.0 rubocop-minitest:0.25.1 rubocop-performance:1.15.2 fpm

    - name: Build deb package
      id: build-deb
      run: |
        version=$(git describe --tags)
        fpm -s dir -t deb -n fzf -v $version --prefix /usr .
        echo "::set-output name=version::$version"

    - name: Upload deb package
      id: upload-deb
      uses: actions/upload-artifact@v2
      with:
        name: fzf-${{ steps.build-deb.outputs.version }}.deb
        path: ./fzf-${{ steps.build-deb.outputs.version }}.deb

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download deb package
      uses: actions/download-artifact@v2
      with:
        name: fzf.deb
        path: .

    - name: Install Ruby gems
      run: sudo gem install --no-document minitest:5.17.0 rubocop:1.43.0 rubocop-minitest:0.25.1 rubocop-performance:1.15.2

    - name: Rubocop
      run: rubocop --require rubocop-minitest --require rubocop-performance

    - name: Unit test
      run: make test

    - name: Integration test
      run: make install && ./install --all && tmux new-session -d && ruby test/test_go.rb --verbose

    - name: Integration test (tcell)
      run: TAGS=tcell make clean install && ruby test/test_go.rb --verbose
