---
name: Build and Test fzf for Ubuntu

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  LANG: C.UTF-8

jobs:
  build:
    outputs:
      version: ${{ steps.build-deb.outputs.VERSION }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.20"

    - name: Install packages
      run: sudo apt-get install --yes build-essential

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Install Ruby gems
      run: sudo gem install --no-document fpm

    - name: Build deb package
      id: build-deb
      run: |
        version=$(git describe --tags || git rev-parse --short HEAD)
        fpm -s dir -t deb -n fzf -v $version --prefix /usr .
        echo "{VERSION}={$version}" >> "$GITHUB_OUTPUT"

    - name: Upload deb package
      id: upload-deb
      uses: actions/upload-artifact@v4
      with:
        name: "fzf_${{ steps.build-deb.outputs.VERSION }}_amd64.deb"
        path: "./fzf_${{ steps.build-deb.outputs.VERSION }}_amd64.deb"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download deb package
      uses: actions/download-artifact@v4
      with:
        name: fzf_${{needs.build.outputs.VERSION}}_amd64.deb
        path: .

    - name: Install deb package and run commands
      run: |
        sudo dpkg -i fzf_${{needs.build.outputs.VERSION}}_amd64.deb
        fzf --version
        eval $(fzf --bash)
        dpkg -L fzf
    
    - name: Install Ruby gems
      run: sudo gem install --no-document minitest:5.17.0 rubocop:1.43.0 rubocop-minitest:0.25.1 rubocop-performance:1.15.2

    - name: Rubocop
      run: rubocop --require rubocop-minitest --require rubocop-performance

    - name: Unit test
      run: make test

    - name: Integration test
      run: make install && ./install --all && tmux new-session -d && ruby test/test_go.rb --verbose

    - name: Integration test (tcell)
      run: TAGS=tcell make clean install && ruby test/test_go.rb --verbose
